services:
  healthlextaticoapi:
    image: ${DOCKER_REGISTRY-}healthlextaticoapi
    container_name: health_lextatico_api
    build:
      context: .
      dockerfile: src/Health.Lextatico.Api/Dockerfile
    ports:
      - 8000:8000
      - 8001:8001
